language: ruby
rvm:
  - 2.2.6
  - 2.3.3
  - rbx
  - ruby-head
  - jruby-head

matrix:
  allow_failures:
    - rvm: rbx
    - rvm: ruby-head
    - rvm: jruby-head

addons:
  code_climate:
    repo_token: 50c636c924d1aa253e29c57822931c1a172cd65675ad66396bba39d255373a58
